# Generated by Django 5.1 on 2024-08-31 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0002_alter_departamento_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=60)),
                ('names', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=60)),
                ('job', models.CharField(choices=[('0', 'Desarrollador'), ('1', 'Diseñador'), ('2', 'Tester'), ('3', 'Analista'), ('4', 'OTRO')], max_length=60, verbose_name='Trabajo')),
                ('image', models.ImageField(upload_to=None, verbose_name='Foto')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
            ],
        ),
    ]
