# Generated by Django 5.1 on 2024-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Apellidos'),
        ),
    ]
