# Generated by Django 5.1 on 2024-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_habilidades_alter_empleado_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidades',
            new_name='Habilidad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='skills',
            field=models.ManyToManyField(blank=True, to='empleados.habilidad'),
        ),
    ]
