# Generated by Django 5.1 on 2024-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_alter_departamento_options_and_more'),
        ('empleados', '0005_rename_habilidades_habilidad_empleado_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['names', 'last_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='departament',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='skills',
            field=models.ManyToManyField(to='empleados.habilidad'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('names', 'department')},
        ),
    ]
