# Generated by Django 5.1 on 2024-09-03 20:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='resume',
            field=ckeditor.fields.RichTextField(default='texto', verbose_name='Hoja de vida'),
            preserve_default=False,
        ),
    ]
