# Generated by Django 5.1 on 2024-09-23 09:57

import applications.empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_empleado_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=applications.empleados.models.CustomImagePath(), validators=[applications.empleados.models.validar_extension_imagen], verbose_name='Foto'),
        ),
    ]
