# Generated by Django 5.1 on 2024-08-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='PruebaBBDD',
        ),
    ]
